// const tempData = [
//   {
//     "key": 0,
//     "translateFields": "extensionName",
//     "fieldsExplain": "ASKWay - Embrace GPT-4's AI Superpower!",
//     "id": "",
//     "fr": "",
//     "ar": "",
//     "hi": "",
//     "bn": "",
//     "lo": "",
//     "vi": ""
//   },
//   {
//     "key": 1,
//     "translateFields": "relateIssues",
//     "fieldsExplain": "相关问题",
//     "id": "Pertanyaan-pertanyaan Terkait",
//     "fr": "questions connexes",
//     "ar": "أسئلة ذات صلة",
//     "hi": "संबंधित सवाल",
//     "bn": "সম্পর্কিত প্রশ্নগুলি",
//     "lo": "ຄໍາຖາມທີ່ກ່ຽວຂ້ອງ",
//     "vi": "Câu hỏi liên quan"
//   },
//   {
//     "key": 2,
//     "translateFields": "askAskway",
//     "fieldsExplain": "询问ASKWay",
//     "id": "Tanya ASKWay",
//     "fr": "Demandez à ASKWay",
//     "ar": "اسأل اسكواي",
//     "hi": "ASKWay से पूछें",
//     "bn": "ASKWay কে জিজ্ঞাসা করুন",
//     "lo": "ຖາມ ASKWay",
//     "vi": "Hỏi ASKWay"
//   },
//   {
//     "key": 3,
//     "translateFields": "summaryPage",
//     "fieldsExplain": "总结页面",
//     "id": "Halaman Ringkasan",
//     "fr": "Page de résumé",
//     "ar": "صفحة الملخص",
//     "hi": "सारांश पृष्ठ",
//     "bn": "সংক্ষিপ্ত পৃষ্ঠা",
//     "lo": "ໜ້າສອນສົບຜົນ",
//     "vi": "Trang Tóm tắt"
//   },
//   {
//     "key": 4,
//     "translateFields": "reload",
//     "fieldsExplain": "重新加载",
//     "id": "Memuat ulang",
//     "fr": "Recharger",
//     "ar": "إعادة التحميل ",
//     "hi": "पुनः लोड करें ",
//     "bn": "পুনরায় লোড করুন ",
//     "lo": "ໂຫຼດໃໝ່",
//     "vi": "Tải lại"
//   },
//   {
//     "key": 5,
//     "translateFields": "searchIssue",
//     "fieldsExplain": "搜索此问题",
//     "id": "Cari Pertanyaan Ini",
//     "fr": "Recherchez cette question.",
//     "ar": "بحث في هذا السؤال.",
//     "hi": "यह प्रश्न खोजें.",
//     "bn": "এই প্রশ্ন অনুসন্ধান করুন.",
//     "lo": "ຄົ້ນຫາຄໍາຖາມນີ້.",
//     "vi": "Tìm kiếm câu hỏi này."
//   },
//   {
//     "key": 6,
//     "translateFields": "askQuestion",
//     "fieldsExplain": "提问",
//     "id": "Bertanya",
//     "fr": "Demander",
//     "ar": "بسأل",
//     "hi": "पूछना",
//     "bn": "জিজ্ঞাসা করুন",
//     "lo": "ຖາມ",
//     "vi": "Hỏi"
//   },
//   {
//     "key": 7,
//     "translateFields": "draft",
//     "fieldsExplain": "草稿",
//     "id": "Draf",
//     "fr": "Brouillon",
//     "ar": "مسودة",
//     "hi": "मसौदा",
//     "bn": "খসড়া",
//     "lo": "ຮ່າງ",
//     "vi": "Bản nháp"
//   },
//   {
//     "key": 8,
//     "translateFields": "copy",
//     "fieldsExplain": "复制",
//     "id": "Menyalin",
//     "fr": "Copie",
//     "ar": "ينسخ",
//     "hi": "प्रतिलिपि",
//     "bn": "কপি",
//     "lo": "ສຳເນົາ",
//     "vi": "Sao chép"
//   },
//   {
//     "key": 9,
//     "translateFields": "copySuc",
//     "fieldsExplain": "复制成功",
//     "id": "Salin berhasil",
//     "fr": "Copie réussie",
//     "ar": "تم النسخ بنجاح",
//     "hi": "प्रतिलिपि सफल",
//     "bn": "কপি সফল",
//     "lo": "ສຳເນົາສຳເລັດແລ້ວ",
//     "vi": "Sao chép thành công"
//   },
//   {
//     "key": 10,
//     "translateFields": "copyFail",
//     "fieldsExplain": "复制失败",
//     "id": "Penyalinan gagal",
//     "fr": "Échec de la copie",
//     "ar": "فشل النسخ",
//     "hi": "प्रतिलिपि विफल",
//     "bn": "অনুলিপি ব্যর্থ হয়েছে",
//     "lo": "ສຳເນົາລົ້ມເຫລວ",
//     "vi": "Sao chép không thành công"
//   },
//   {
//     "key": 11,
//     "translateFields": "retry",
//     "fieldsExplain": "重新生成",
//     "id": "Mencoba kembali",
//     "fr": "Recommencez",
//     "ar": "أعد المحاولة",
//     "hi": "पुन: प्रयास करें",
//     "bn": "পুনরায় চেষ্টা করা",
//     "lo": "ລອງໃໝ່",
//     "vi": "Thử lại"
//   },
//   {
//     "key": 12,
//     "translateFields": "regeneration",
//     "fieldsExplain": "重新回答",
//     "id": "Regenerasi Respon",
//     "fr": "Régénérer la réponse",
//     "ar": "تجديد الاستجابة",
//     "hi": "प्रतिक्रिया पुनः उत्पन्न करें",
//     "bn": "প্রতিক্রিয়া পুনরুত্পাদন",
//     "lo": "ຟື້ນຟູການຕອບໂຕ້",
//     "vi": "Tạo lại phản hồi"
//   },
//   {
//     "key": 13,
//     "translateFields": "stop",
//     "fieldsExplain": "停止",
//     "id": "Berhenti",
//     "fr": "Arrêt",
//     "ar": "قف",
//     "hi": "रुकना",
//     "bn": "থামো",
//     "lo": "ຢຸດ",
//     "vi": "Dừng lại"
//   },
//   {
//     "key": 14,
//     "translateFields": "close",
//     "fieldsExplain": "关闭",
//     "id": "Menutup",
//     "fr": "Fermer",
//     "ar": "يغلق",
//     "hi": "बंद करना",
//     "bn": "বন্ধ",
//     "lo": "ປິດ",
//     "vi": "Đóng"
//   },
//   {
//     "key": 15,
//     "translateFields": "result",
//     "fieldsExplain": "结果",
//     "id": "Hasil",
//     "fr": "Résultat",
//     "ar": "نتيجة",
//     "hi": "परिणाम",
//     "bn": "ফলাফল",
//     "lo": "ຜົນໄດ້ຮັບ",
//     "vi": "Kết quả"
//   },
//   {
//     "key": 16,
//     "translateFields": "original",
//     "fieldsExplain": "原文",
//     "id": "Asli",
//     "fr": "Original",
//     "ar": "إبداعي",
//     "hi": "मूल",
//     "bn": "আসল",
//     "lo": "ຕົ້ນສະບັບ",
//     "vi": "Nguyên bản"
//   },
//   {
//     "key": 17,
//     "translateFields": "continueChat",
//     "fieldsExplain": "继续聊天",
//     "id": "Lanjutkan di Obrolan",
//     "fr": "Continuer dans le chat",
//     "ar": "تواصل في الدردشة",
//     "hi": "चैट में जारी रखें",
//     "bn": "চ্যাটে চালিয়ে যান",
//     "lo": "ສືບຕໍ່ໃນການສົນທະນາ",
//     "vi": "Tiếp tục trong Trò chuyện"
//   },
//   {
//     "key": 18,
//     "translateFields": "edit",
//     "fieldsExplain": "编辑",
//     "id": "Sunting",
//     "fr": "Modifier",
//     "ar": "يحرر",
//     "hi": "संपादन करना",
//     "bn": "সম্পাদনা করুন",
//     "lo": "ແກ້ໄຂ",
//     "vi": "Biên tập"
//   },
//   {
//     "key": 19,
//     "translateFields": "requestError",
//     "fieldsExplain": "系统繁忙",
//     "id": "Sistem sedang sibuk",
//     "fr": "Le système est occupé",
//     "ar": "النظام مشغول",
//     "hi": "सिस्टम व्यस्त है",
//     "bn": "সিস্টেম ব্যস্ত",
//     "lo": "ລະບົບບໍ່ຫວ່າງ",
//     "vi": "Hệ thống đang bận"
//   },
//   {
//     "key": 20,
//     "translateFields": "sendMsg",
//     "fieldsExplain": "发送",
//     "id": "Mengirim",
//     "fr": "Envoyer",
//     "ar": "يرسل",
//     "hi": "भेजना",
//     "bn": "পাঠান",
//     "lo": "ສົ່ງ",
//     "vi": "Gửi"
//   },
//   {
//     "key": 21,
//     "translateFields": "wrapMsg",
//     "fieldsExplain": "换行",
//     "id": "bungkus",
//     "fr": "wrap",
//     "ar": "أدخل",
//     "hi": " रैप",
//     "bn": "wrap",
//     "lo": "wrap",
//     "vi": " bọc"
//   },
//   {
//     "key": 22,
//     "translateFields": "aiInputInfo",
//     "fieldsExplain": "有任何问题都可以问我",
//     "id": "Tanyakan padaku jika ada masalah",
//     "fr": "Posez-moi des problèmes",
//     "ar": "تسألني أي مشاكل",
//     "hi": "मुझसे कोई भी समस्या पूछें",
//     "bn": "কোন সমস্যা আমাকে জিজ্ঞাসা করুন",
//     "lo": "ຖາມຂ້ອຍທຸກບັນຫາ",
//     "vi": "Hỏi tôi bất kỳ vấn đề"
//   },
//   {
//     "key": 23,
//     "translateFields": "pleaseInput",
//     "fieldsExplain": "请输入",
//     "id": "Silakan masukkan",
//     "fr": "Veuillez entrer",
//     "ar": "الرجاء إدخال",
//     "hi": "الرجاء إدخال",
//     "bn": "দয়া করে প্রবেশ করুন ",
//     "lo": "ກະລຸນາປ້ອນ ",
//     "vi": "Vui lòng nhập"
//   },
//   {
//     "key": 24,
//     "translateFields": "history",
//     "fieldsExplain": "会话历史",
//     "id": "",
//     "fr": "Histoire",
//     "ar": "تاريخ",
//     "hi": "इतिहास",
//     "bn": "ইতিহাস",
//     "lo": "ປະຫວັດສາດ",
//     "vi": "Lịch sử"
//   },
//   {
//     "key": 25,
//     "translateFields": "historyTitle",
//     "fieldsExplain": "会话历史",
//     "id": "Riwayat Percakapan",
//     "fr": "Historique des conversations",
//     "ar": "تاريخ المحادثة",
//     "hi": "बातचीत का इतिहास",
//     "bn": "কথোপকথনের ইতিহাস",
//     "lo": "ປະຫວັດການສົນທະນາ",
//     "vi": "Lịch sử trò chuyện"
//   },
//   {
//     "key": 26,
//     "translateFields": "newSession",
//     "fieldsExplain": "新会话",
//     "id": "Obrolan Baru",
//     "fr": "Nouvelle discussion",
//     "ar": "دردشة جديدة",
//     "hi": "नई चैट",
//     "bn": "নতুন চ্যাট",
//     "lo": "ສົນທະນາໃໝ່",
//     "vi": "Cuộc trò truyện mới"
//   },
//   {
//     "key": 27,
//     "translateFields": "hisRecord",
//     "fieldsExplain": "会话历史",
//     "id": "Riwayat Percakapan",
//     "fr": "Histoire",
//     "ar": "تاريخ",
//     "hi": "इतिहास",
//     "bn": "ইতিহাস",
//     "lo": "ປະຫວັດສາດ",
//     "vi": "Lịch sử"
//   },
//   {
//     "key": 28,
//     "translateFields": "infoWord",
//     "fieldsExplain": "提示词",
//     "id": "Anjuran",
//     "fr": "Instructions",
//     "ar": "حث",
//     "hi": "संकेतों",
//     "bn": "প্রম্পট",
//     "lo": "ເຕືອນ",
//     "vi": "Lời nhắc"
//   },
//   {
//     "key": 29,
//     "translateFields": "infoWordTemp",
//     "fieldsExplain": "提示词模版",
//     "id": "Prompts",
//     "fr": "Instructions",
//     "ar": "حث",
//     "hi": "संकेतों",
//     "bn": "প্রম্পট",
//     "lo": "ເຕືອນ",
//     "vi": "Lời nhắc"
//   },
//   {
//     "key": 30,
//     "translateFields": "search",
//     "fieldsExplain": "搜索",
//     "id": "Mencari",
//     "fr": "Recherche",
//     "ar": "يبحث",
//     "hi": "खोज",
//     "bn": "অনুসন্ধান করুন",
//     "lo": "ຊອກຫາ",
//     "vi": "Tìm kiếm"
//   },
//   {
//     "key": 31,
//     "translateFields": "stopgenerator",
//     "fieldsExplain": "停止回复",
//     "id": "Hentikan Generasi",
//     "fr": "Arrêter la génération",
//     "ar": "وقف الجيل",
//     "hi": "जनरेशन बंद करो",
//     "bn": "স্টপ জেনারেশন",
//     "lo": "ຢຸດການຜະລິດ",
//     "vi": "Dừng thế hệ"
//   },
//   {
//     "key": 32,
//     "translateFields": "like",
//     "fieldsExplain": "点赞",
//     "id": "Menyukai",
//     "fr": "Comme",
//     "ar": "يحب",
//     "hi": "पसंद",
//     "bn": "লাইক",
//     "lo": "ມັກ",
//     "vi": "Giống"
//   },
//   {
//     "key": 33,
//     "translateFields": "pages",
//     "fieldsExplain": "页",
//     "id": "halaman",
//     "fr": "pages",
//     "ar": "إجمالي",
//     "hi": "पृष्ठ",
//     "bn": "পৃষ্ঠা",
//     "lo": "ໜ້າ",
//     "vi": "trang"
//   },
//   {
//     "key": 34,
//     "translateFields": "disLike",
//     "fieldsExplain": "踩",
//     "id": "Benci",
//     "fr": "Ne pas aimer",
//     "ar": "لم يعجبنى",
//     "hi": "नापसन्द",
//     "bn": "অপছন্দ",
//     "lo": "ບໍ່ມັກ",
//     "vi": "Không thích"
//   },
//   {
//     "key": 35,
//     "translateFields": "total",
//     "fieldsExplain": "共",
//     "id": "Jumlahnya",
//     "fr": "total",
//     "ar": "الصفحات",
//     "hi": "कुल",
//     "bn": "মোট ",
//     "lo": "ມັນມີ",
//     "vi": "Tổng số"
//   },
//   {
//     "key": 36,
//     "translateFields": "delSuccess",
//     "fieldsExplain": "删除成功",
//     "id": "Penghapusan berhasil",
//     "fr": "Suppression réussie",
//     "ar": "تم الحذف بنجاح",
//     "hi": "विलोपन सफल",
//     "bn": "মোছা সফল",
//     "lo": "ການລຶບສຳເລັດແລ້ວ",
//     "vi": "Xóa thành công"
//   },
//   {
//     "key": 37,
//     "translateFields": "all",
//     "fieldsExplain": "全部",
//     "id": "semua-",
//     "fr": "tout",
//     "ar": "الكل",
//     "hi": "सब",
//     "bn": "الكل",
//     "lo": "ທັງໝົດ",
//     "vi": "toàn bộ"
//   },
//   {
//     "key": 38,
//     "translateFields": "yourChoose",
//     "fieldsExplain": "您选择的文本",
//     "id": "Teks yang telah Anda pilih",
//     "fr": "Le texte que vous avez sélectionné",
//     "ar": "النص الذي حددته",
//     "hi": "आपने जो टेक्स्ट चुना है",
//     "bn": "আপনার নির্বাচিত পাঠ্য",
//     "lo": "ຂໍ້ຄວາມທີ່ທ່ານເລືອກ",
//     "vi": "Văn bản bạn đã chọn"
//   },
//   {
//     "key": 39,
//     "translateFields": "txtOp",
//     "fieldsExplain": "您希望对文本进行什么操作？",
//     "id": "Apa yang Anda ingin lakukan dengan teks ini？",
//     "fr": "Que souhaitez-vous faire avec ce texte ?",
//     "ar": "ما العمل الذي ترغب في القيام به مع هذا النص؟ ",
//     "hi": "आप इस पाठ के साथ क्या करना चाहेंगे? ",
//     "bn": "আপনি কি এই লেখার সাথে কী করতে চান?",
//     "lo": "ທ່ານຢາກຕ້ອງການທີ່ຈະຈັດການຂໍ້ມູນນີ້ໄດ້ຫຼືບໍ່?",
//     "vi": "Bạn muốn thực hiện thao tác gì với văn bản này?"
//   },
//   {
//     "key": 40,
//     "translateFields": "outputLanguage",
//     "fieldsExplain": "输出语言",
//     "id": "Bahasa Output-",
//     "fr": "Langue de sortie",
//     "ar": "لغة الإخراج",
//     "hi": "आउटपुट भाषा ",
//     "bn": "আউটপুট ভাষা",
//     "lo": "ພາສາອອກສອນ",
//     "vi": "Ngôn ngữ đầu ra"
//   },
//   {
//     "key": 41,
//     "translateFields": "welcomeMessage",
//     "fieldsExplain": "您想聊些什么？我会尽力为您提供最好的回答和帮助！",
//     "id": "Apa yang ingin Anda bicarakan? Saya akan berusaha memberikan jawaban dan bantuan terbaik!",
//     "fr": "De quoi voulez-vous discuter ? Je ferai de mon mieux pour vous fournir les meilleures réponses et vous aider !",
//     "ar": "ما الذي ترغب في الحديث عنه؟ سأبذل قصارى جهدي لتقديم أفضل الإجابات والمساعدة!",
//     "hi": "आप किस बारे में चैट करना चाहेंगे? मैं आपको सबसे अच्छे जवाब और सहायता प्रदान करने की कोशिश करूंगा!",
//     "bn": "আপনি কী কথা বলতে চান? আমি আপনাকে সেরা উত্তর এবং সাহায্য দেওয়ার চেষ্টা করব!",
//     "lo": "ທ່ານຮັບວັນທີ່ຕ້ອງການສົນທະນາຫຼືບັນທຶກຫຼືຊ່ວຍເຫຼືອງໃນການສົນທະນາ? ຂໍຂອບໃຈທ່ານສໍາລັບການມາດໃຊ້ຄວາມຍຸດທະສາດແລະຊ່ວຍຊ່ວຍທີ່ດີທີ່ສຸດ!",
//     "vi": "Bạn muốn trò chuyện về điều gì? Tôi sẽ cố gắng cung cấp những câu trả lời và sự giúp đỡ tốt nhất cho bạn!"
//   },
//   {
//     "key": 42,
//     "translateFields": "welcomeMessageGpt4",
//     "fieldsExplain": "我是GPT-4，比GPT-3.5更聪明，需要我帮你解决什么问题？",
//     "id": "Saya adalah GPT-4, lebih pintar daripada GPT-3.5, bagaimana saya bisa membantu Anda?",
//     "fr": "Je suis GPT-4, plus intelligent que GPT-3.5, comment puis-je vous aider?",
//     "ar": "أنا GPT-4، أذكى من GPT-3.5، كيف يمكنني مساعدتك؟",
//     "hi": "मैं GPT-4 हूँ, GPT-3.5 से अधिक बुद्धिमान हूँ, मैं आपकी कैसे सहायता कर सकता हूँ?",
//     "bn": "আমি GPT-4, GPT-3.5 এর চেয়ে বুদ্ধিমান, আপনাকে কিভাবে সাহায্য করতে পারি?",
//     "lo": "ຂໍຂອບໃຈ, ຂໍ້ມູນຂອງຂ້ອຍເປັນ GPT-4, ສູງສຸດການຮວມຂອງ GPT-3.5, ຂໍ້ມູນນີ້ຈະເຮັດວຽກໃຫ້ເຈົ້າໄດ້ຊ່ວຍຫຍັງ?",
//     "vi": "Tôi là GPT-4, thông minh hơn GPT-3.5, tôi có thể giúp bạn như thế nào?"
//   },
//   {
//     "key": 43,
//     "translateFields": "answer",
//     "fieldsExplain": "回答",
//     "id": "Bertanya",
//     "fr": "Demander",
//     "ar": "بسأل",
//     "hi": "पूछना",
//     "bn": "জিজ্ঞাসা করুন",
//     "lo": "ຖາມ",
//     "vi": "Hỏi"
//   },
//   {
//     "key": 44,
//     "translateFields": "accountInformation",
//     "fieldsExplain": "账户信息",
//     "id": "Akun",
//     "fr": "Compte",
//     "ar": "حساب",
//     "hi": "खाता",
//     "bn": "হিসাব",
//     "lo": "ບັນຊີ",
//     "vi": "Tài khoản"
//   },
//   {
//     "key": 45,
//     "translateFields": "accountInformationTitle",
//     "fieldsExplain": "账户信息",
//     "id": "Profil",
//     "fr": "Profil",
//     "ar": "حساب تعريفي",
//     "hi": "प्रोफ़ाइल",
//     "bn": "প্রোফাইল",
//     "lo": "ໂປຣໄຟລ໌",
//     "vi": "Hồ sơ"
//   },
//   {
//     "key": 46,
//     "translateFields": "changePassword",
//     "fieldsExplain": "修改密码",
//     "id": "Ganti kata sandi",
//     "fr": "Changer le mot de passe",
//     "ar": "تغيير كلمة المرور",
//     "hi": "पासवर्ड बदलें",
//     "bn": "পাসওয়ার্ড পরিবর্তন করুন",
//     "lo": "ປ່ຽນ​ລະ​ຫັດ​ຜ່ານ",
//     "vi": "Đổi mật khẩu"
//   },
//   {
//     "key": 47,
//     "translateFields": "generic",
//     "fieldsExplain": "通用",
//     "id": "Umum",
//     "fr": "Général",
//     "ar": "عام",
//     "hi": "सामान्य",
//     "bn": "সাধারণ",
//     "lo": "ທົ່ວໄປ",
//     "vi": "Tổng quan"
//   },
//   {
//     "key": 48,
//     "translateFields": "searchSettings",
//     "fieldsExplain": "搜索设置",
//     "id": "Pengaturan pencarian",
//     "fr": "Paramètres de recherche",
//     "ar": "إعدادات البحث",
//     "hi": "खोज सेंटिंग",
//     "bn": "অনুসন্ধান সেটিংস",
//     "lo": "ຄົ້ນຫາການຕັ້ງຄ່າ",
//     "vi": "Thiết lập tìm kiếm"
//   },
//   {
//     "key": 49,
//     "translateFields": "sidebar",
//     "fieldsExplain": "侧边栏",
//     "id": "Bilah samping",
//     "fr": "Barre latérale",
//     "ar": "الشريط الجانبي",
//     "hi": "साइड बार",
//     "bn": "সাইডবার",
//     "lo": "ແຖບດ້ານຂ້າງ",
//     "vi": "Thanh bên"
//   },
//   {
//     "key": 50,
//     "translateFields": "aboutUs",
//     "fieldsExplain": "关于我们",
//     "id": "Tentang kami",
//     "fr": "À propos de nous",
//     "ar": "معلومات عنا",
//     "hi": "हमारे बारे में",
//     "bn": "আমাদের সম্পর্কে",
//     "lo": "ກ່ຽວ​ກັບ​ພວກ​ເຮົາ",
//     "vi": "Về chúng tôi"
//   },
//   {
//     "key": 51,
//     "translateFields": "email",
//     "fieldsExplain": "电子邮箱",
//     "id": "Alamat email",
//     "fr": "Adresse e-mail",
//     "ar": "عنوان البريد الإلكتروني",
//     "hi": "मेल पता",
//     "bn": "ইমেইল ঠিকানা",
//     "lo": "ທີ່​ຢູ່​ອີ​ເມວ",
//     "vi": "Địa chỉ email"
//   },
//   {
//     "key": 52,
//     "translateFields": "name",
//     "fieldsExplain": "名字",
//     "id": "Nama",
//     "fr": "Nom",
//     "ar": "اسم",
//     "hi": "नाम",
//     "bn": "নাম",
//     "lo": "ຊື່",
//     "vi": "Tên"
//   },
//   {
//     "key": 53,
//     "translateFields": "deleteAccount",
//     "fieldsExplain": "删除账号",
//     "id": "Hapus akun",
//     "fr": "Supprimer le compte",
//     "ar": "حذف الحساب",
//     "hi": "खाता हटा दो",
//     "bn": "হিসাব মুছে ফেলা",
//     "lo": "ລຶບບັນຊີ",
//     "vi": "Xóa tài khoản"
//   },
//   {
//     "key": 54,
//     "translateFields": "deleteInfo",
//     "fieldsExplain": "删除账号后，您的信息将不再保留，也无法再使用服务，请谨慎删除",
//     "id": "Setelah menghapus akun Anda, informasi Anda tidak akan disimpan lagi, dan Anda tidak akan dapat menggunakan layanan ini lagi. Harap hapus dengan hati-hati.",
//     "fr": "Après la suppression de votre compte, vos informations ne seront plus conservées et vous ne pourrez plus utiliser le service. Veuillez supprimer avec prudence.",
//     "ar": "بعد حذف حسابك، لن يتم الاحتفاظ بمعلوماتك بعد الآن، ولن تتمكن من استخدام الخدمة مرة أخرى. يرجى الحذف بحذر.",
//     "hi": "आपका खाता हटाने के बाद, आपकी जानकारी बरकरार नहीं रखी जाएगी और आप दोबारा सेवा का उपयोग नहीं कर पाएंगे। कृपया सावधानी से हटाएँ.",
//     "bn": "আপনার অ্যাকাউন্ট মুছে ফেলার পরে, আপনার তথ্য আর রাখা হবে না, এবং আপনি আবার পরিষেবাটি ব্যবহার করতে পারবেন না। সাবধানে মুছে দিন.",
//     "lo": "ຫຼັງ​ຈາກ​ການ​ລຶບ​ບັນ​ຊີ​ຂອງ​ທ່ານ​, ຂໍ້​ມູນ​ຂອງ​ທ່ານ​ຈະ​ບໍ່​ມີ​ຕໍ່​ໄປ​ອີກ​ແລ້ວ​, ແລະ​ທ່ານ​ຈະ​ບໍ່​ສາ​ມາດ​ນໍາ​ໃຊ້​ບໍ​ລິ​ການ​ໄດ້​ອີກ​. ກະລຸນາລຶບດ້ວຍຄວາມລະມັດລະວັງ.",
//     "vi": "Sau khi xóa tài khoản, thông tin của bạn sẽ không được lưu giữ nữa và bạn sẽ không thể sử dụng lại dịch vụ. Vui lòng xóa một cách thận trọng."
//   },
//   {
//     "key": 55,
//     "translateFields": "save",
//     "fieldsExplain": "保存",
//     "id": "Menyimpan",
//     "fr": "Sauvegarder",
//     "ar": "يحفظ",
//     "hi": "बचाना",
//     "bn": "সংরক্ষণ",
//     "lo": "ບັນທຶກ",
//     "vi": "Cứu"
//   },
//   {
//     "key": 56,
//     "translateFields": "cancel",
//     "fieldsExplain": "取消",
//     "id": "Membatalkan",
//     "fr": "Annuler",
//     "ar": "يلغي",
//     "hi": "रद्द करना",
//     "bn": "বাতিল করুন",
//     "lo": "ຍົກເລີກ",
//     "vi": "Hủy bỏ"
//   },
//   {
//     "key": 57,
//     "translateFields": "originalPassword",
//     "fieldsExplain": "原密码",
//     "id": "Kata sandi asli",
//     "fr": "Mot de passe d'origine",
//     "ar": "كلمة المرور الأصلية",
//     "hi": "मूल पासवर्ड",
//     "bn": "আসল পাসওয়ার্ড",
//     "lo": "ລະຫັດຜ່ານຕົ້ນສະບັບ",
//     "vi": "Mật khẩu gốc"
//   },
//   {
//     "key": 58,
//     "translateFields": "password",
//     "fieldsExplain": "新密码",
//     "id": "Kata sandi baru",
//     "fr": "Nouveau mot de passe",
//     "ar": "كلمة المرور الجديدة",
//     "hi": "नया पासवर्ड",
//     "bn": "নতুন পাসওয়ার্ড",
//     "lo": "ລະຫັດຜ່ານໃໝ່",
//     "vi": "Mật khẩu mới"
//   },
//   {
//     "key": 59,
//     "translateFields": "confirmPassword",
//     "fieldsExplain": "确认新密码",
//     "id": "Konfirmasi sandi",
//     "fr": "Confirmez le mot de passe",
//     "ar": "تأكيد كلمة المرور",
//     "hi": "पासवर्ड की पुष्टि कीजिये",
//     "bn": "পাসওয়ার্ড নিশ্চিত করুন",
//     "lo": "ຢືນ​ຢັນ​ລະ​ຫັດ",
//     "vi": "Xác nhận mật khẩu"
//   },
//   {
//     "key": 60,
//     "translateFields": "defaultLanguage",
//     "fieldsExplain": "默认语言",
//     "id": "Bahasa bawaan",
//     "fr": "Langage par défaut",
//     "ar": "اللغة الافتراضية",
//     "hi": "डिफ़ॉल्ट भाषा",
//     "bn": "নির্ধারিত ভাষা",
//     "lo": "ພາສາເລີ່ມຕົ້ນ",
//     "vi": "Ngôn ngữ mặc định"
//   },
//   {
//     "key": 61,
//     "translateFields": "chatLineBreakShortcut",
//     "fieldsExplain": "聊天换行快捷键",
//     "id": "Kirim Pintasan",
//     "fr": "Envoyer un raccourci",
//     "ar": "إرسال الاختصار",
//     "hi": "शॉर्टकट भेजें",
//     "bn": "শর্টকাট পাঠান",
//     "lo": "ສົ່ງທາງລັດ",
//     "vi": "Gửi phím tắt"
//   },
//   {
//     "key": 62,
//     "translateFields": "searchPanel",
//     "fieldsExplain": "搜索面板",
//     "id": "Panel pencarian",
//     "fr": "Panneau de recherche",
//     "ar": "لوحة البحث",
//     "hi": "खोज पैनल",
//     "bn": "অনুসন্ধান প্যানেল",
//     "lo": "ກະດານຄົ້ນຫາ",
//     "vi": "Bảng tìm kiếm"
//   },
//   {
//     "key": 63,
//     "translateFields": "searchInfo",
//     "fieldsExplain": "在搜索引擎结果页展示ASKWay搜索结果",
//     "id": "Menampilkan hasil pencarian ASKWay di halaman hasil mesin pencari",
//     "fr": "Affichage des résultats de recherche ASKWay dans les pages de résultats des moteurs de recherche",
//     "ar": "عرض نتائج بحث ASKWay في صفحات نتائج محرك البحث",
//     "hi": "खोज इंजन परिणाम पृष्ठों में ASKWay खोज परिणाम प्रदर्शित करना",
//     "bn": "সার্চ ইঞ্জিন ফলাফল পৃষ্ঠাগুলিতে ASKWay অনুসন্ধান ফলাফল প্রদর্শন করা হচ্ছে",
//     "lo": "ການສະແດງຜົນການຄົ້ນຫາ ASKWay ໃນຫນ້າຜົນໄດ້ຮັບຂອງເຄື່ອງຈັກຊອກຫາ",
//     "vi": "Hiển thị kết quả tìm kiếm ASKWay trong các trang kết quả của công cụ tìm kiếm"
//   },
//   {
//     "key": 64,
//     "translateFields": "searchResult",
//     "fieldsExplain": "搜索结果",
//     "id": "Hasil pencarian",
//     "fr": "Résultats de recherche",
//     "ar": "نتائج البحث",
//     "hi": "खोज परिणाम",
//     "bn": "অনুসন্ধানের ফলাফল",
//     "lo": "ຜົນການຄົ້ນຫາ",
//     "vi": "Kết quả tìm kiếm"
//   },
//   {
//     "key": 65,
//     "translateFields": "limit20",
//     "fieldsExplain": "额度大于20条时自动询问ASKWay",
//     "id": "Tanyakan secara otomatis kepada ASKWay ketika jumlah yang tersisa lebih dari 20.",
//     "fr": "Renseignez-vous automatiquement auprès d'ASKWay lorsque la quantité restante est supérieure à 20.",
//     "ar": "استفسر تلقائيا مع ASKWay عندما تكون الكمية المتبقية أكبر من 20.",
//     "hi": "जब शेष मात्रा 20 से अधिक हो तो स्वचालित रूप से ASKWay से पूछताछ करें।",
//     "bn": "অবশিষ্ট পরিমাণ 20-এর বেশি হলে স্বয়ংক্রিয়ভাবে ASKWay-এর সাথে জিজ্ঞাসা করুন।",
//     "lo": "ສອບຖາມອັດຕະໂນມັດກັບ ASKWay ເມື່ອປະລິມານທີ່ຍັງເຫຼືອແມ່ນຫຼາຍກວ່າ 20.",
//     "vi": "Tự động hỏi ASKWay khi số lượng còn lại lớn hơn 20."
//   },
//   {
//     "key": 66,
//     "translateFields": "alwaysAsk",
//     "fieldsExplain": "总是询问ASKWay",
//     "id": "Selalu bertanya dengan ASKWay",
//     "fr": "Renseignez-vous toujours auprès d'ASKWay",
//     "ar": "استفسر دائمًا مع ASKWay",
//     "hi": "हमेशा ASKWay से पूछताछ करें",
//     "bn": "সর্বদা ASKWay এর সাথে অনুসন্ধান করুন",
//     "lo": "ສອບຖາມກັບ ASKWay ສະເໝີ",
//     "vi": "Luôn hỏi ASKWay"
//   },
//   {
//     "key": 67,
//     "translateFields": "ManuallyAsk",
//     "fieldsExplain": "手动询问ASKWay",
//     "id": "Tanyakan secara manual dengan ASKWay",
//     "fr": "Renseignez-vous manuellement auprès d'ASKWay",
//     "ar": "الاستعلام يدويًا باستخدام ASKWay",
//     "hi": "ASKWay से मैन्युअल रूप से पूछताछ करें",
//     "bn": "ASKWay এর সাথে ম্যানুয়ালি জিজ্ঞাসা করুন",
//     "lo": "ສອບຖາມດ້ວຍຕົນເອງກັບ ASKWay",
//     "vi": "Truy vấn thủ công với ASKWay"
//   },
//   {
//     "key": 68,
//     "translateFields": "usDescFirst",
//     "fieldsExplain": "ASKWay（中文：问道），是一个基于当前领先的AI技术构建的机器人，当前使用了来自 OpenAI 和其他同类AI的最新官方API。",
//     "id": "ASKWay (Bahasa Indonesia: Tanya Jalan), adalah sebuah robot yang dibangun berdasarkan teknologi AI terkini, saat ini menggunakan API resmi terbaru dari OpenAI dan AI serupa lainnya.",
//     "fr": "ASKWay (en français: Demande Chemin), est un robot construit sur la base des dernières technologies d'IA, utilisant actuellement les API officielles les plus récentes d'OpenAI et d'autres IA similaires.",
//     "ar": "ASKWay (بالعربية: اسأل الطريق)، هو روبوت يعتمد على أحدث تقنيات الذكاء الاصطناعي، ويستخدم حاليًا واجهة برمجة التطبيقات الرسمية الأحدث من OpenAI وغيرها من الذكاء الاصطناعي المماثل.",
//     "hi": "ASKWay (हिंदी में: मार्ग पूछो), एक रोबोट है जो वर्तमान में उच्चतम AI तकनीक पर आधारित है, जो वर्तमान में OpenAI और अन्य समान AI के नवीनतम आधिकारिक API का उपयोग करता है।",
//     "bn": "ASKWay (বাংলা: পথ জিজ্ঞাসা করুন), এটি একটি রোবট যা সর্বশেষ AI প্রযুক্তির উপর ভিত্তি করে তৈরি করা হয়েছে, যা বর্তমানে OpenAI এবং অন্যান্য একই ধরনের AI এর সর্বশেষ অফিসিয়াল API ব্যবহার করে।",
//     "lo": "ASKWay (ລາວ: ສອນທາງ), ແມ່ນໂຮດທີ່ສ້າງມີຄວາມສະຫງວນສະຫນັບສະຫນູນອີກສອນທາງຂອງຕົນກະທົບການສຳລັບການໃຊ້ການສ້າງຂອງ AI ທີ່ປະສົບການ, ປະມານນີ້ເປັນ API ສຳລັບການໃຊ້ທີ່ເປັນທາງສູງສຸດຂອງ OpenAI ແລະ AI ອື່ນໆ.",
//     "vi": "ASKWay (bằng tiếng Việt: Hỏi Đường), là một robot được xây dựng dựa trên"
//   },
//   {
//     "key": 69,
//     "translateFields": "usDescSecond",
//     "fieldsExplain": "我们的使命是让对话变得更加智能，让用户享受智能服务的便捷和高效。",
//     "id": "Misi kami adalah membuat percakapan menjadi lebih cerdas, sehingga pengguna dapat menikmati layanan cerdas yang nyaman dan efisien.",
//     "fr": "Misi kami adalah membuat percakapan menjadi lebih cerdas, sehingga pengguna dapat menikmati layanan cerdas yang nyaman dan efisien.",
//     "ar": "مهمتنا هي جعل الحوار أكثر ذكاءً، حتى يتمكن المستخدمون من الاستمتاع بخدمة ذكية مريحة وفعالة.",
//     "hi": "مهمتنا هي جعل الحوار أكثر ذكاءً، حتى يتمكن المستخدمون من الاستمتاع بخدمة ذكية مريحة وفعالة.",
//     "bn": "আমাদের মিশন হলো কথোপকথনকে আরও স্মার্ট করা, যাতে ব্যবহারকারীরা সুবিধাজনক এবং দক্ষ সেবা উপভোগ করতে পারেন।",
//     "lo": "ຄົນພະຍາຍາມຂອງພວກເຮົາແມ່ນເຮັດສະຫຼຸບໃຫຍ່ການສົນທະນາທີ່ໄດ້, ທີ່ຈະໃຫ້ຜູ້ໃຊ້ສາມາດໃຊ້ບໍລິການສະຫຼຸບທີ່ສູງສຸດແລະຄວາມດີກວ່ານັ້ນ.",
//     "vi": "Nhiệm vụ của chúng tôi là làm cho cuộc trò chuyện trở nên thông minh hơn, để người dùng có thể tận hưởng dịch vụ thông minh tiện lợi và hiệu quả."
//   },
//   {
//     "key": 70,
//     "translateFields": "usDescThird",
//     "fieldsExplain": "我们相信，ASKWay能够成为你最好的生活和工作助手。",
//     "id": "Kami percaya bahwa ASKWay dapat menjadi asisten terbaik Anda dalam kehidupan dan pekerjaan. ",
//     "fr": "Nous croyons que ASKWay peut devenir votre meilleur assistant pour la vie et le travail. ",
//     "ar": "نحن نعتقد أن ASKWay يمكن أن يصبح أفضل مساعد لك في الحياة والعمل. ",
//     "hi": "نحن نعتقد أن ASKWay يمكن أن يصبح أفضل مساعد لك في الحياة والعمل. ",
//     "bn": "আমরা বিশ্বাস করি যে ASKWay আপনার জীবন এবং কাজের জন্য সেরা সহায়ক হতে পারে।",
//     "lo": "ພວກເຮົາໄດ້ເຫັນວິທີການວອນຈັດສະຫຼັບສາມາດເປັນຊຸດຂອງທ່ານທີ່ດີທີ່ສຸດໃນການຊິດຂາດແລະການເຮັດວຽກ. ",
//     "vi": "Chúng tôi tin rằng ASKWay có thể trở thành trợ lý tốt nhất của bạn trong cuộc sống và công việc."
//   },
//   {
//     "key": 71,
//     "translateFields": "confirmDel",
//     "fieldsExplain": "删除账号",
//     "id": "Hapus akun",
//     "fr": "Supprimer le compte",
//     "ar": "حذف الحساب",
//     "hi": "खाता हटा दो",
//     "bn": "হিসাব মুছে ফেলা",
//     "lo": "ລຶບບັນຊີ",
//     "vi": "Xóa tài khoản"
//   },
//   {
//     "key": 72,
//     "translateFields": "confirmDelInfo",
//     "fieldsExplain": "删除账号后，您的信息将不再保留，也无法再使用服务，请谨慎删除",
//     "id": "Setelah menghapus akun Anda, informasi Anda tidak akan disimpan lagi, dan Anda tidak akan dapat menggunakan layanan ini lagi. Harap hapus dengan hati-hati.",
//     "fr": "Après la suppression de votre compte, vos informations ne seront plus conservées et vous ne pourrez plus utiliser le service. Veuillez supprimer avec prudence.",
//     "ar": "بعد حذف حسابك، لن يتم الاحتفاظ بمعلوماتك بعد الآن، ولن تتمكن من استخدام الخدمة مرة أخرى. يرجى الحذف بحذر.",
//     "hi": "आपका खाता हटाने के बाद, आपकी जानकारी बरकरार नहीं रखी जाएगी और आप दोबारा सेवा का उपयोग नहीं कर पाएंगे। कृपया सावधानी से हटाएँ.",
//     "bn": "আপনার অ্যাকাউন্ট মুছে ফেলার পরে, আপনার তথ্য আর রাখা হবে না, এবং আপনি আবার পরিষেবাটি ব্যবহার করতে পারবেন না। সাবধানে মুছে দিন.",
//     "lo": "ຫຼັງ​ຈາກ​ການ​ລຶບ​ບັນ​ຊີ​ຂອງ​ທ່ານ​, ຂໍ້​ມູນ​ຂອງ​ທ່ານ​ຈະ​ບໍ່​ມີ​ຕໍ່​ໄປ​ອີກ​ແລ້ວ​, ແລະ​ທ່ານ​ຈະ​ບໍ່​ສາ​ມາດ​ນໍາ​ໃຊ້​ບໍ​ລິ​ການ​ໄດ້​ອີກ​. ກະລຸນາລຶບດ້ວຍຄວາມລະມັດລະວັງ.",
//     "vi": "Sau khi xóa tài khoản, thông tin của bạn sẽ không được lưu giữ nữa và bạn sẽ không thể sử dụng lại dịch vụ. Vui lòng xóa một cách thận trọng."
//   },
//   {
//     "key": 73,
//     "translateFields": "enterNickName",
//     "fieldsExplain": "名称必填",
//     "id": "Nama harus diisi",
//     "fr": "Le nom est obligatoire",
//     "ar": "اسم مطلوب",
//     "hi": "नाम भरना अनिवार्य है",
//     "bn": "নাম পূরণ করা আবশ্যক",
//     "lo": "ຕໍ່ໄປຈຳເປັນຕ້ອງການຊື່",
//     "vi": "Tên là bắt buộc"
//   },
//   {
//     "key": 74,
//     "translateFields": "signOut",
//     "fieldsExplain": "退出登录",
//     "id": "Keluar dari akun",
//     "fr": "Déconnexion",
//     "ar": "تسجيل الخروج",
//     "hi": "लॉगआउट करें",
//     "bn": "লগ আউট করুন",
//     "lo": "ອອກຈາກບັນຊີ",
//     "vi": "Đăng xuất"
//   },
//   {
//     "key": 75,
//     "translateFields": "pwdReq",
//     "fieldsExplain": "密码必填",
//     "id": "Kata sandi harus diisi",
//     "fr": "Le mot de passe est obligatoire",
//     "ar": "كلمة المرور مطلوبة",
//     "hi": "पासवर्ड भरना अनिवार्य है",
//     "bn": "পাসওয়ার্ড পূরণ করা আবশ্যক",
//     "lo": "ຕໍ່ໄປຈຳເປັນຕ້ອງການລະຫັດຜ່ານ",
//     "vi": "Mật khẩu là bắt buộc"
//   },
//   {
//     "key": 76,
//     "translateFields": "password6",
//     "fieldsExplain": "密码至少6位字符",
//     "id": "Panjang kata sandi minimum adalah 6 karakter.",
//     "fr": "Longueur du mot de passe d'au moins 6 caractères",
//     "ar": "طول كلمة المرور لا يقل عن 6 أحرف",
//     "hi": "अपना पासवर्ड दर्ज करें",
//     "bn": "আপনার পাসওয়ার্ড দিন",
//     "lo": "ກະລຸນາໃສ່ລະຫັດຜ່ານຂອງທ່ານ",
//     "vi": "Độ dài mật khẩu ít nhất 6 ký tự"
//   },
//   {
//     "key": 77,
//     "translateFields": "password20",
//     "fieldsExplain": "密码最多20位字符",
//     "id": "Panjang kata sandi maksimum adalah 20 karakter.",
//     "fr": "Longueur du mot de passe jusqu'à 20 caractères",
//     "ar": "طول كلمة المرور يصل إلى 20 حرفًا",
//     "hi": "पासवर्ड की लंबाई 20 अक्षर तक",
//     "bn": "পাসওয়ার্ডের দৈর্ঘ্য 20 অক্ষর পর্যন্ত",
//     "lo": "ຄວາມຍາວລະຫັດຜ່ານສູງສຸດ 20 ຕົວອັກສອນ",
//     "vi": "Độ dài mật khẩu tối đa 20 ký tự"
//   },
//   {
//     "key": 78,
//     "translateFields": "InconsistentPassword",
//     "fieldsExplain": "密码不一致",
//     "id": "Kata sandi tidak cocok.",
//     "fr": "Le mot de passe ne correspond pas.",
//     "ar": "كلمات السر لا تتطابق.",
//     "hi": "पासवर्ड मेल नहीं खाया।",
//     "bn": "পাসওয়ার্ড মেলে না.",
//     "lo": "ລະຫັດຜ່ານບໍ່ກົງກັນ.",
//     "vi": "Mật khẩu không trùng khớp."
//   },
//   {
//     "key": 79,
//     "translateFields": "passwordModify",
//     "fieldsExplain": "修改成功",
//     "id": "Berhasil diubah",
//     "fr": "Modification réussie",
//     "ar": "تم التعديل بنجاح",
//     "hi": "सफलतापूर्वक संशोधित किया गया",
//     "bn": "সফলভাবে পরিবর্তন করা হয়েছে",
//     "lo": "ປັບປຸງສົບຜົນສໍາເລັດ",
//     "vi": "Thay đổi thành công"
//   },
//   {
//     "key": 80,
//     "translateFields": "noCount",
//     "fieldsExplain": "剩余次数不足",
//     "id": "Jumlah tersisa tidak mencukupi",
//     "fr": "Nombre de tentatives restantes insuffisant",
//     "ar": "العدد المتبقي غير كافٍ",
//     "hi": "शेष बार अपर्याप्त है",
//     "bn": "বাকি সংখ্যা পর্যাপ্ত নয়",
//     "lo": "ຈຳນວນທີ່ເຫຼືອກຫຼາຍບໍ່ພໍ່ຄ້າ",
//     "vi": "Số lần còn lại không đủ"
//   },
//   {
//     "key": 81,
//     "translateFields": "contentRequired",
//     "fieldsExplain": "所有内容必填",
//     "id": "Semua konten harus diisi",
//     "fr": "Tous les champs sont obligatoires",
//     "ar": "جميع المحتويات مطلوبة",
//     "hi": "सभी सामग्री भरना अनिवार्य है",
//     "bn": "সমস্ত বিষয়বস্তু পূরণ করা আবশ্যক",
//     "lo": "ຕ້ອງການລາຍລະອຽດທັງຫມົດຕໍ່ໄປຈຳເປັນຕ້ອງການການໃສ່",
//     "vi": "Tất cả nội dung là bắt buộc"
//   },
//   {
//     "key": 82,
//     "translateFields": "exceptionError",
//     "fieldsExplain": "未知错误",
//     "id": "Kesalahan tidak diketahui",
//     "fr": "Erreur inconnue",
//     "ar": "خطأ غير معروف",
//     "hi": "अज्ञात त्रुटि",
//     "bn": "অজানা ত্রুটি",
//     "lo": "ຜິດພາດທີ່ບໍ່ຮູ້ຈັກ",
//     "vi": "Lỗi không xác định"
//   },
//   {
//     "key": 83,
//     "translateFields": "tomorrowTry",
//     "fieldsExplain": "GPT-4当月次数已用完，下个月会再赠送哦~",
//     "id": "GPT-4 sudah habis bulan ini, dan akan diberikan lagi bulan depan.",
//     "fr": "GPT-4 a été épuisé ce mois-ci et sera à nouveau administré le mois prochain.",
//     "ar": "تم استخدام GPT-4 هذا الشهر، وسيتم إعطاؤه مرة أخرى الشهر المقبل.",
//     "hi": "GPT-4 का उपयोग इस महीने हो चुका है, और अगले महीने फिर से दिया जाएगा।",
//     "bn": "GPT-4 এই মাসে ব্যবহার করা হয়েছে, এবং পরের মাসে আবার দেওয়া হবে।",
//     "lo": "GPT-4 ໄດ້ຖືກນໍາໃຊ້ຫມົດໃນເດືອນນີ້, ແລະຈະໃຫ້ອີກເທື່ອຫນຶ່ງໃນເດືອນຫນ້າ.",
//     "vi": "GPT-4 đã được sử dụng hết trong tháng này và sẽ được cấp lại vào tháng sau."
//   },
//   {
//     "key": 84,
//     "translateFields": "unknownError",
//     "fieldsExplain": "未知错误",
//     "id": "Kesalahan tidak diketahui",
//     "fr": "Erreur inconnue",
//     "ar": "خطأ غير معروف",
//     "hi": "अज्ञात त्रुटि",
//     "bn": "অজানা ত্রুটি",
//     "lo": "ຜິດພາດທີ່ບໍ່ຮູ້ຈັກ",
//     "vi": "Lỗi không xác định"
//   },
//   {
//     "key": 85,
//     "translateFields": "noData",
//     "fieldsExplain": "无数据",
//     "id": "Tidak ada data yang tersedia",
//     "fr": "Pas de données disponibles",
//     "ar": "لا توجد بيانات متاحة",
//     "hi": "कोई डेटा उपलब्ध नहीं है",
//     "bn": "কোন তথ্য নেই",
//     "lo": "ບໍ່ມີຂໍ້ມູນທີ່ມີຢູ່",
//     "vi": "Không có dữ liệu"
//   },
//   {
//     "key": 86,
//     "translateFields": "logoutSuccessful",
//     "fieldsExplain": "退出成功",
//     "id": "Berhasil keluar",
//     "fr": "Déconnexion réussie",
//     "ar": "تم الخروج بنجاح",
//     "hi": "सफलतापूर्वक बाहर निकलें",
//     "bn": "সফলভাবে প্রস্থান করুন",
//     "lo": "ອອກຈາກລະບົບສຳເລັດ",
//     "vi": "Thoát thành công"
//   },
//   {
//     "key": 87,
//     "translateFields": "notLogged",
//     "fieldsExplain": "未登录",
//     "id": "Belum masuk",
//     "fr": "Non connecté",
//     "ar": "غير مسجل الدخول",
//     "hi": "लॉग इन नहीं हुआ",
//     "bn": "লগইন হয়নি",
//     "lo": "ບໍ່ໄດ້ເຂົ້າສູ່ລະບົບ",
//     "vi": "Chưa đăng nhập"
//   },
//   {
//     "key": 88,
//     "translateFields": "quantity",
//     "fieldsExplain": "剩余次数",
//     "id": "Jumlah sisa",
//     "fr": "Nombre de fois restantes",
//     "ar": "العدد المتبقي",
//     "hi": "शेष बार",
//     "bn": "বাকি সংখ্যা",
//     "lo": "ຈໍານວນທີ່ເຫຼືອ",
//     "vi": "Số lần còn lại"
//   },
//   {
//     "key": 89,
//     "translateFields": "logOut",
//     "fieldsExplain": "退出登录",
//     "id": "Keluar dari akun",
//     "fr": "Déconnexion",
//     "ar": "تسجيل الخروج",
//     "hi": "लॉगआउट करें",
//     "bn": "লগআউট করুন",
//     "lo": "ອອກຈາກລະບົບ",
//     "vi": "ອອກຈາກລະບົບ"
//   },
//   {
//     "key": 90,
//     "translateFields": "manuallyAsk",
//     "fieldsExplain": "手动询问ASKWay",
//     "id": "Tanyakan secara manual dengan ASKWay",
//     "fr": "Renseignez-vous manuellement auprès d'ASKWay",
//     "ar": "الاستعلام يدويًا باستخدام ASKWay",
//     "hi": "ASKWay से मैन्युअल रूप से पूछताछ करें",
//     "bn": "ASKWay এর সাথে ম্যানুয়ালি জিজ্ঞাসা করুন",
//     "lo": "ສອບຖາມດ້ວຍຕົນເອງກັບ ASKWay",
//     "vi": "Truy vấn thủ công với ASKWay"
//   },
//   {
//     "key": 91,
//     "translateFields": "propaganda",
//     "fieldsExplain": "你工作、生活中的AI助手",
//     "id": "Asisten AI Anda untuk pekerjaan dan kehidupan",
//     "fr": "Votre assistant IA pour le travail et la vie",
//     "ar": "مساعد الذكاء الاصطناعي الخاص بك للعمل والحياة",
//     "hi": "ईमेल या पासवर्ड अमान्य है.",
//     "bn": "ইমেল বা পাসওয়ার্ড অবৈধ.",
//     "lo": "ອີເມວ ຫຼືລະຫັດຜ່ານບໍ່ຖືກຕ້ອງ.",
//     "vi": "Trợ lý AI của bạn cho công việc và cuộc sống"
//   },
//   {
//     "key": 92,
//     "translateFields": "perMonth",
//     "fieldsExplain": "每月",
//     "id": "per bulan",
//     "fr": "par mois",
//     "ar": "شهرياً",
//     "hi": "प्रति माह",
//     "bn": "প্রতি মাসে",
//     "lo": "ເດືອນທີ່",
//     "vi": "mỗi tháng"
//   },
//   {
//     "key": 93,
//     "translateFields": "signIn",
//     "fieldsExplain": "登录",
//     "id": "Masuk",
//     "fr": "Se connecter",
//     "ar": "تسجيل الدخول",
//     "hi": "दाखिल करना",
//     "bn": "সাইন ইন করুন",
//     "lo": "ເຂົ້າ​ສູ່​ລະ​ບົບ",
//     "vi": "Đăng nhập"
//   },
//   {
//     "key": 94,
//     "translateFields": "click",
//     "fieldsExplain": "点击",
//     "id": "klik",
//     "fr": "cliquer",
//     "ar": "نقر",
//     "hi": "क्लिक करें",
//     "bn": "ক্লিক করুন",
//     "lo": "ກົດ",
//     "vi": "nhấp chuột"
//   },
//   {
//     "key": 95,
//     "translateFields": "and",
//     "fieldsExplain": "和",
//     "id": "dan",
//     "fr": "et",
//     "ar": "و",
//     "hi": "और",
//     "bn": "এবং",
//     "lo": "ແລະ",
//     "vi": "và"
//   },
//   {
//     "key": 96,
//     "translateFields": "fixed",
//     "fieldsExplain": "固定ASKWay",
//     "id": "ASKWay tetap",
//     "fr": "ASKWay fixe",
//     "ar": "ASKWay ثابت",
//     "hi": "स्थिर ASKWay",
//     "bn": "স্থির ASKWay",
//     "lo": "ASKWay ປົກກະຕິ",
//     "vi": "ASKWay cố định"
//   },
//   {
//     "key": 97,
//     "translateFields": "skip",
//     "fieldsExplain": "跳过",
//     "id": "lewatkan",
//     "fr": "passer",
//     "ar": "تخطى",
//     "hi": "छोड़ें",
//     "bn": "এড়ান",
//     "lo": "ຂ້າມປະຕິບັດ",
//     "vi": "bỏ qua"
//   },
//   {
//     "key": 98,
//     "translateFields": "searchEnhance",
//     "fieldsExplain": "搜索增强",
//     "id": "Peningkatan Pencarian",
//     "fr": "Amélioration de la recherche",
//     "ar": "تعزيز البحث",
//     "hi": "खोज में सुधार",
//     "bn": "অনুসন্ধান উন্নতি",
//     "lo": "ການຊອກຫາສຸດທິພາບ",
//     "vi": "Tăng cường tìm kiếm"
//   },
//   {
//     "key": 99,
//     "translateFields": "searchEnhanceDes",
//     "fieldsExplain": "在网络搜索引擎结果页面上，提供相关问题及解释。",
//     "id": "Pada halaman hasil mesin pencari web, berikan pertanyaan terkait dan penjelasan. ",
//     "fr": "Sur la page de résultats du moteur de recherche web, fournissez des questions et des explications connexes.",
//     "ar": "في صفحة نتائج محرك البحث على الويب، قدم أسئلة ذات صلة وشروحات. ",
//     "hi": "वेब खोज इंजन परिणाम पृष्ठ पर, संबंधित प्रश्न और स्पष्टीकरण प्रदान करें",
//     "bn": "ওয়েব অনুসন্ধান ইঞ্জিন ফলাফল পৃষ্ঠায়, সম্পর্কিত প্রশ্ন এবং ব্যাখ্যা দিন",
//     "lo": "ຕາຕະລາງຜົນການຄົ້ນຫາຈາກເວັບໄຊທ໌, ສາມາດໃຫ້ຄຳຖາມທີ່ເກັບການຕົວຢ່າງແລະຄຳອະທິບາຍທີ່ກ່ຽວຂ້ອງໄດ້. ",
//     "vi": "Trên trang kết quả tìm kiếm của công cụ tìm kiếm web, cung cấp câu hỏi liên quan và giải thích."
//   },
//   {
//     "key": 100,
//     "translateFields": "textProcessing",
//     "fieldsExplain": "Al快速文本处理",
//     "id": "Pemrosesan Teks Cepat ",
//     "fr": "Traitement rapide de texte Al",
//     "ar": "معالجة النص السريعة Al",
//     "hi": "अल तेज़ पाठ प्रोसेसिंग",
//     "bn": "তাড়াতাড়ি পাঠ্য প্রক্রিয়া Al",
//     "lo": "ການປະຕິບັດຂໍ້ຄວາມດ້ວຍຄວາມຍ່ອຍ Al",
//     "vi": "Xử lý văn bản nhanh chóng Al"
//   },
//   {
//     "key": 101,
//     "translateFields": "textProcessingDes",
//     "fieldsExplain": "选择文本进行一键摘要、翻译、解释、语法纠正等操作。Al快速完成文本处理任务。",
//     "id": "Pilih teks untuk ringkasan satu klik, terjemahan, penjelasan, koreksi tata bahasa, dan operasi lainnya. AI dengan cepat menyelesaikan tugas pemrosesan teks.",
//     "fr": "Sélectionnez du texte pour un résumé en un clic, une traduction, une explication, une correction grammaticale et autres opérations. L'IA effectue rapidement les tâches de traitement de texte.",
//     "ar": "اختر النص للملخص بنقرة واحدة، الترجمة، التفسير، إصلاح القواعد النحوية، وغيرها من العمليات. الذكاء الاصطناعي ينجز بسرعة مهام معالجة النصوص.",
//     "hi": "एक क्लिक सारांश, अनुवाद, व्याख्या, व्याकरण सुधार और अन्य ऑपरेशन के लिए पाठ का चयन करें। एआई तेजी से पाठ प्रसंस्करण कार्यों को पूरा करता है।",
//     "bn": "এক ক্লিকে সারসংক্ষেপ, অনুবাদ, ব্যাখ্যা, ব্যাকরণ শুদ্ধি এবং অন্যান্য কার্যক্রমের জন্য পাঠ নির্বাচন করুন। AI দ্রুততমে পাঠ প্রসেসিং টাস্কগুলি সম্পন্ন করে।",
//     "lo": "ເລືອກຂໍ້ຄວາມເພື່ອບັນທຶກຢູ່ຕົວເລກສອງຄິດ, ການແປພາສາ, ການຮຽກຮ້ອງ, ການສົ່ງສານພາສາ ແລະ ໂຄງສ້າງອື່ນໆ. ໄອຣິກແມ່ນຕົວເລກ AI ທີ່ໃຊ້ໃນການບໍລິການການຊໍ້າສະຖາງຂໍ້ຄວາມດ້ວຍຄວາມຢ້ານໆ.",
//     "vi": "Chọn văn bản để tóm tắt, dịch, giải thích, sửa lỗi ngữ pháp và các thao tác khác một cách nhanh chóng. Trí tuệ nhân tạo sẽ hoàn thành tác vụ xử lý văn bản một cách nhanh chóng."
//   },
//   {
//     "key": 102,
//     "translateFields": "chatASKWay",
//     "fieldsExplain": "与ASKWay聊天",
//     "id": "Chat dengan ASKWay",
//     "fr": "Discutez avec ASKWay",
//     "ar": "الدردشة مع ASKWay",
//     "hi": "الدردشة مع ASKWay",
//     "bn": "الدردشة مع ASKWay",
//     "lo": "ສົນທະນາການສອງກັບ ASKWay",
//     "vi": "Trò chuyện với ASKWay"
//   },
//   {
//     "key": 103,
//     "translateFields": "chatASKWayDes",
//     "fieldsExplain": "ASKWay与您沟通和互动，帮助回答您的问题并释放您的创造力！",
//     "id": "ASKWay berkomunikasi dan berinteraksi dengan Anda untuk membantu menjawab pertanyaan Anda dan mengeluarkan kreativitas Anda!",
//     "fr": "ASKWay communique et interagit avec vous pour vous aider à répondre à vos questions et libérer votre créativité !",
//     "ar": "تتواصل ASKWay وتتفاعل معك لمساعدتك في الإجابة على أسئلتك وإطلاق إبداعك!",
//     "hi": "ASKWay आपके सवालों के जवाब देने और आपकी रचनात्मकता को उन्मुख करने के लिए आपके साथ संवाद और संवाद करता है!",
//     "bn": "ASKWay আপনার প্রশ্নের উত্তর দেওয়া এবং আপনার সৃজনশীলতা মুক্ত করতে আপনার সাথে যোগাযোগ ও আপাতত করে!",
//     "lo": "ASKWay ສົນທະນາແລະສົບຜົນການກໍາຫນົດສຳລັບການຕອບກັບຄ່າຄົນທີ່ສາມາດຊ່ວຍຄວາມສຳລັບທ່ານແລະເຮັດໃຫ້ຄວາມສ່ວນຂອງທ່ານ!",
//     "vi": "ASKWay giao tiếp và tương tác với bạn để giúp bạn trả lời câu hỏi và khai phá sự sáng tạo của bạn!"
//   },
//   {
//     "key": 104,
//     "translateFields": "notSupported",
//     "fieldsExplain": "当前空白标签不支持AI聊天。请打开任意一个网页以激活AI聊天窗口。",
//     "id": "Tab kosong saat ini tidak mendukung obrolan Al. Silakan buka halaman web untuk mengaktifkan jendela obrolan Al. ",
//     "fr": "L'onglet actuel vide ne prend pas en charge le chat Al. Veuillez ouvrir une page Web pour activer la fenêtre de chat Al.",
//     "ar": "العلامة التبويب الحالية الفارغة لا تدعم الدردشة الذكية. يرجى فتح صفحة ويب لتنشيط نافذة الدردشة الذكية. ",
//     "hi": "वर्तमान खाली टैब एल चैट का समर्थन नहीं करती है। कृपया एल चैट विंडो सक्रिय करने के लिए एक वेबपेज खोलें।",
//     "bn": "বর্তমান খালি ট্যাবটি এল চ্যাট সমর্থন করে না। এল চ্যাট উইন্ডো সক্রিয় করতে একটি ওয়েবপেজ খুলুন।",
//     "lo": "ປະເພດປະຕິບັດທີ່ມີປະຕິບັດ Al ບໍ່ສະຫມັກ. ກະລຸນາເປີດໜ້າເວັບໄຊ້ເພື່ອເປີດໃຊ້ຖານຂ້ອຍ Al. ",
//     "vi": "ab trống hiện tại không hỗ trợ trò chuyện Al. Vui lòng mở trang web để kích hoạt cửa sổ trò chuyện Al."
//   },
//   {
//     "key": 105,
//     "translateFields": "onlineSearch",
//     "fieldsExplain": "联网查询",
//     "id": "Pencarian online",
//     "fr": "Recherche en ligne",
//     "ar": "البحث عبر الإنترنت",
//     "hi": "ऑनलाइन खोज",
//     "bn": "অনলাইন অনুসন্ধান",
//     "lo": "ການຄົ້ນຫາອອນເຕັມອອນລາຍ",
//     "vi": "Tìm kiếm trực tuyến"
//   },
//   {
//     "key": 106,
//     "translateFields": "findAnswers",
//     "fieldsExplain": "在网络上查找答案",
//     "id": "emukan jawaban di web",
//     "fr": "emukan jawaban di web",
//     "ar": "العثور على إجابات على الويب",
//     "hi": "वेब पर जवाब ढूंढें",
//     "bn": "ওয়েবে উত্তর খুঁজুন",
//     "lo": "ຄົ້ນຫາຄວາມຕົກໃຈໃນເວັບ",
//     "vi": "Tìm kiếm câu trả lời trên web"
//   },
//   {
//     "key": 107,
//     "translateFields": "searchingOnline",
//     "fieldsExplain": "正在联网搜索",
//     "id": "Mencari di Internet",
//     "fr": "Recherche sur Internet",
//     "ar": "البحث على الإنترنت",
//     "hi": "البحث على الإنترنت",
//     "bn": "ইন্টারনেটে অনুসন্ধান",
//     "lo": "ຄົ້ນຫາຢືນຍັນໃນອິນເຕີເນັດ",
//     "vi": "Tìm kiếm trên Internet"
//   },
//   {
//     "key": 108,
//     "translateFields": "noMoreData",
//     "fieldsExplain": "没有更多数据",
//     "id": "Tidak ada data lagi",
//     "fr": "Plus de données",
//     "ar": "لا مزيد من البيانات",
//     "hi": "और डेटा नहीं",
//     "bn": "আর কোন ডেটা নেই",
//     "lo": "ບໍ່ມີຂໍ້ມູນເດັ່ນນີ້",
//     "vi": "Không còn dữ liệu"
//   },
//   {
//     "key": 109,
//     "translateFields": "msgNotification",
//     "fieldsExplain": "消息通知",
//     "id": "Pemberitahuan pesan",
//     "fr": "Notification de message",
//     "ar": "إشعار الرسالة",
//     "hi": "संदेश सूचना",
//     "bn": "বার্তা বিজ্ঞপ্তি",
//     "lo": "ການແຈ້ງເຕືອນຂໍ້ຄວາມ",
//     "vi": "Thông báo tin nhắn"
//   },
//   {
//     "key": 110,
//     "translateFields": "loading",
//     "fieldsExplain": "加载中",
//     "id": "Memuat",
//     "fr": "Chargement",
//     "ar": "جار التحميل",
//     "hi": "लोड हो रहा है",
//     "bn": "লোড হচ্ছে",
//     "lo": "ການໂຫລດການອັບໂຫລດ",
//     "vi": "Đang tải"
//   },
//   {
//     "key": 111,
//     "translateFields": "originLanguage",
//     "fieldsExplain": "原文语言",
//     "id": "Sumber",
//     "fr": "Source",
//     "ar": "مصدر",
//     "hi": "स्रोत",
//     "bn": "উৎস",
//     "lo": "ທີ່ມາ",
//     "vi": "Nguồn"
//   },
//   {
//     "key": 112,
//     "translateFields": "detectAuto",
//     "fieldsExplain": "自动检测",
//     "id": "Deteksi otomatis",
//     "fr": "Détection automatique",
//     "ar": "اكتشاف تلقائي",
//     "hi": "ऑटो का पता लगाने",
//     "bn": "স্বয়ং সনাক্ত",
//     "lo": "ກວດຫາອັດຕະໂນມັດ",
//     "vi": "Tự động phát hiện"
//   },
//   {
//     "key": 113,
//     "translateFields": "targetLanguage",
//     "fieldsExplain": "目标语言",
//     "id": "Target",
//     "fr": "Cible",
//     "ar": "هدف",
//     "hi": "लक्ष्य",
//     "bn": "টার্গেট",
//     "lo": "ເປົ້າ​ຫມາຍ",
//     "vi": "Mục tiêu"
//   },
//   {
//     "key": 114,
//     "translateFields": "autoTranslateTargetLanguage",
//     "fieldsExplain": "自动翻译成目标语言",
//     "id": "Terjemahan Otomatis Bahasa Target",
//     "fr": "Langue cible de la traduction automatique",
//     "ar": "الترجمة التلقائية للغة الهدف",
//     "hi": "स्वचालित अनुवाद लक्ष्य भाषा",
//     "bn": "স্বয়ংক্রিয় অনুবাদ লক্ষ্য ভাষা",
//     "lo": "ແປອັດຕະໂນມັດພາສາເປົ້າຫມາຍ",
//     "vi": "Tự động dịch ngôn ngữ mục tiêu"
//   },
//   {
//     "key": 115,
//     "translateFields": "alwaysDisplayTranBtn",
//     "fieldsExplain": "总是展示翻译按钮",
//     "id": "Selalu Tampilkan Tombol Terjemahan",
//     "fr": "Toujours afficher le bouton de traduction",
//     "ar": "قم دائمًا بعرض زر الترجمة",
//     "hi": "हमेशा अनुवाद बटन प्रदर्शित करें",
//     "bn": "সর্বদা অনুবাদ বোতাম প্রদর্শন করুন",
//     "lo": "ສະແດງປຸ່ມແປພາສາສະເໝີ",
//     "vi": "Luôn hiển thị nút dịch"
//   }
// ]
